# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Veri_Tabani.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Veri_Tabani_Window(object):
    def setupUi(self, Veri_Tabani_Window):
        Veri_Tabani_Window.setObjectName("Veri_Tabani_Window")
        Veri_Tabani_Window.resize(1940, 1010)
        Veri_Tabani_Window.setMaximumSize(QtCore.QSize(1940, 1010))
        Veri_Tabani_Window.setStyleSheet("/* ---------------------------------------------------------------------------\n"
"\n"
"    WARNING! File created programmatically. All changes made in this file will be lost!\n"
"\n"
"    Created by the qtsass compiler v0.3.0\n"
"\n"
"    The definitions are in the \"qdarkstyle.qss._styles.scss\" module\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"/* Light Style - QDarkStyleSheet ------------------------------------------ */\n"
"/*\n"
"\n"
"See Qt documentation:\n"
"\n"
"  - https://doc.qt.io/qt-5/stylesheet.html\n"
"  - https://doc.qt.io/qt-5/stylesheet-reference.html\n"
"  - https://doc.qt.io/qt-5/stylesheet-examples.html\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"/* Reset elements ------------------------------------------------------------\n"
"\n"
"Resetting everything helps to unify styles across different operating systems\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"* {\n"
"  padding: 0px;\n"
"  margin: 0px;\n"
"  border: 0px;\n"
"  border-style: none;\n"
"  border-image: none;\n"
"  outline: 0;\n"
"  font-size: 20px;\n"
"}\n"
"\n"
"/* specific reset for elements inside QToolBar */\n"
"QToolBar * {\n"
"  margin: 0px;\n"
"  padding: 0px;\n"
"}\n"
"\n"
"/* QWidget ----------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QWidget {\n"
"  background-color: #19232D;\n"
"  border: 0px solid #455364;\n"
"  padding: 0px;\n"
"  color: #E0E1E3;\n"
"  selection-background-color: #346792;\n"
"  selection-color: #E0E1E3;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"  selection-background-color: #26486B;\n"
"  selection-color: #9DA9B5;\n"
"}\n"
"\n"
"QWidget::item:selected {\n"
"  background-color: #346792;\n"
"}\n"
"\n"
"QWidget::item:hover:!selected {\n"
"  background-color: #1A72BB;\n"
"}\n"
"\n"
"/* QMainWindow ------------------------------------------------------------\n"
"\n"
"This adjusts the splitter in the dock widget, not qsplitter\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmainwindow\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QMainWindow::separator {\n"
"  background-color: #455364;\n"
"  border: 0px solid #19232D;\n"
"  spacing: 0px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QMainWindow::separator:hover {\n"
"  background-color: #60798B;\n"
"  border: 0px solid #1A72BB;\n"
"}\n"
"\n"
"QMainWindow::separator:horizontal {\n"
"  width: 5px;\n"
"  margin-top: 2px;\n"
"  margin-bottom: 2px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_separator_vertical.png\");\n"
"}\n"
"\n"
"QMainWindow::separator:vertical {\n"
"  height: 5px;\n"
"  margin-left: 2px;\n"
"  margin-right: 2px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_separator_horizontal.png\");\n"
"}\n"
"\n"
"/* QToolTip ---------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtooltip\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolTip {\n"
"  background-color: #346792;\n"
"  color: #E0E1E3;\n"
"  /* If you remove the border property, background stops working on Windows */\n"
"  border: none;\n"
"  /* Remove padding, for fix combo box tooltip */\n"
"  padding: 0px;\n"
"  /* Remove opacity, fix #174 - may need to use RGBA */\n"
"}\n"
"\n"
"/* QStatusBar -------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qstatusbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QStatusBar {\n"
"  border: 1px solid #455364;\n"
"  /* Fixes Spyder #9120, #9121 */\n"
"  background: #455364;\n"
"  /* Fixes #205, white vertical borders separating items */\n"
"}\n"
"\n"
"QStatusBar::item {\n"
"  border: none;\n"
"}\n"
"\n"
"QStatusBar QToolTip {\n"
"  background-color: #1A72BB;\n"
"  border: 1px solid #19232D;\n"
"  color: #19232D;\n"
"  /* Remove padding, for fix combo box tooltip */\n"
"  padding: 0px;\n"
"  /* Reducing transparency to read better */\n"
"  opacity: 230;\n"
"}\n"
"\n"
"QStatusBar QLabel {\n"
"  /* Fixes Spyder #9120, #9121 */\n"
"  background: transparent;\n"
"}\n"
"\n"
"/* QCheckBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qcheckbox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QCheckBox {\n"
"  background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"  spacing: 4px;\n"
"  outline: none;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"}\n"
"\n"
"QCheckBox:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QCheckBox QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"  margin-left: 2px;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"\n"
"\n"
"/* QGroupBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qgroupbox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QGroupBox {\n"
"  font-weight: bold;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  margin-top: 6px;\n"
"  margin-bottom: 4px;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"  subcontrol-origin: margin;\n"
"  subcontrol-position: top left;\n"
"  left: 4px;\n"
"  padding-left: 2px;\n"
"  padding-right: 4px;\n"
"  padding-top: -4px;\n"
"}\n"
"\n"
"QGroupBox::indicator {\n"
"  margin-left: 2px;\n"
"  margin-top: 2px;\n"
"  padding: 0;\n"
"  height: 14px;\n"
"  width: 14px;\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked:hover, QGroupBox::indicator:unchecked:focus, QGroupBox::indicator:unchecked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked_focus.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:unchecked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:checked {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:checked:hover, QGroupBox::indicator:checked:focus, QGroupBox::indicator:checked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QGroupBox::indicator:checked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_disabled.png\");\n"
"}\n"
"\n"
"/* QRadioButton -----------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qradiobutton\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QRadioButton {\n"
"  background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"  spacing: 4px;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"  border: none;\n"
"  outline: none;\n"
"  font-size: 20px;\n"
"}\n"
"\n"
"QRadioButton:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QRadioButton:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"  border: none;\n"
"  outline: none;\n"
"}\n"
"\n"
"QRadioButton QWidget {\n"
"  background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"  spacing: 0px;\n"
"  padding: 0px;\n"
"  outline: none;\n"
"  border: none;\n"
"}\n"
"\n"
"\n"
"\n"
"/* QMenuBar ---------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmenubar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QMenuBar {\n"
"  background-color: #455364;\n"
"  padding: 2px;\n"
"  border: 1px solid #19232D;\n"
"  color: #E0E1E3;\n"
"  selection-background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenuBar:focus {\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QMenuBar::item {\n"
"  background: transparent;\n"
"  padding: 4px;\n"
"  margin-right: 8px;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"  padding: 4px;\n"
"  background: transparent;\n"
"  border: 0px solid #455364;\n"
"  background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenuBar::item:pressed {\n"
"  padding: 4px;\n"
"  border: 0px solid #455364;\n"
"  background-color: #1A72BB;\n"
"  color: #E0E1E3;\n"
"  margin-bottom: 0px;\n"
"  padding-bottom: 0px;\n"
"}\n"
"\n"
"/* QMenu ------------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qmenu\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QMenu {\n"
"  border: 0px solid #455364;\n"
"  color: #E0E1E3;\n"
"  margin: 0px;\n"
"  background-color: #37414F;\n"
"  selection-background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenu::separator {\n"
"  height: 1px;\n"
"  background-color: #60798B;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QMenu::item {\n"
"  background-color: #37414F;\n"
"  padding: 4px 24px 4px 28px;\n"
"  /* Reserve space for selection border */\n"
"  border: 1px transparent #455364;\n"
"}\n"
"\n"
"QMenu::item:selected {\n"
"  color: #E0E1E3;\n"
"  background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenu::item:pressed {\n"
"  background-color: #1A72BB;\n"
"}\n"
"\n"
"QMenu::icon {\n"
"  padding-left: 10px;\n"
"  width: 14px;\n"
"  height: 14px;\n"
"}\n"
"\n"
"QMenu::indicator {\n"
"  padding-left: 8px;\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  /* non-exclusive indicator = check box style indicator (see QActionGroup::setExclusive) */\n"
"  /* exclusive indicator = radio button style indicator (see QActionGroup::setExclusive) */\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:hover, QMenu::indicator:non-exclusive:unchecked:focus, QMenu::indicator:non-exclusive:unchecked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:unchecked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:hover, QMenu::indicator:non-exclusive:checked:focus, QMenu::indicator:non-exclusive:checked:pressed {\n"
"  border: none;\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:checked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:indeterminate {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:indeterminate:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:non-exclusive:indeterminate:focus, QMenu::indicator:non-exclusive:indeterminate:hover, QMenu::indicator:non-exclusive:indeterminate:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked {\n"
"  image: url(\":/qss_icons/dark/rc/radio_unchecked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:hover, QMenu::indicator:exclusive:unchecked:focus, QMenu::indicator:exclusive:unchecked:pressed {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_unchecked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:unchecked:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/radio_unchecked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_checked.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:hover, QMenu::indicator:exclusive:checked:focus, QMenu::indicator:exclusive:checked:pressed {\n"
"  border: none;\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_checked_focus.png\");\n"
"}\n"
"\n"
"QMenu::indicator:exclusive:checked:disabled {\n"
"  outline: none;\n"
"  image: url(\":/qss_icons/dark/rc/radio_checked_disabled.png\");\n"
"}\n"
"\n"
"QMenu::right-arrow {\n"
"  margin: 5px;\n"
"  padding-left: 12px;\n"
"  image: url(\":/qss_icons/dark/rc/arrow_right.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"}\n"
"\n"
"/* QAbstractItemView ------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qcombobox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractItemView {\n"
"  alternate-background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QAbstractItemView QLineEdit {\n"
"  padding: 2px;\n"
"}\n"
"\n"
"/* QAbstractScrollArea ----------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qabstractscrollarea\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractScrollArea {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  /* fix #159 */\n"
"  padding: 2px;\n"
"  /* remove min-height to fix #244 */\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QAbstractScrollArea:disabled {\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"/* QScrollArea ------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QScrollArea QWidget QWidget:disabled {\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"/* QScrollBar -------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qscrollbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QScrollBar:horizontal {\n"
"  height: 16px;\n"
"  margin: 2px 16px 2px 16px;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"  background-color: #19232D;\n"
"  width: 16px;\n"
"  margin: 16px 2px 16px 2px;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"  background-color: #60798B;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"  background-color: #346792;\n"
"  border: #346792;\n"
"  border-radius: 4px;\n"
"  min-width: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"  background-color: #60798B;\n"
"  border: 1px solid #455364;\n"
"  min-height: 8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"  background-color: #346792;\n"
"  border: #346792;\n"
"  border-radius: 4px;\n"
"  min-height: 8px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"  margin: 0px 0px 0px 0px;\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_right_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover, QScrollBar::add-line:horizontal:on {\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_right.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: right;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_down_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover, QScrollBar::add-line:vertical:on {\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: bottom;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"  margin: 0px 3px 0px 3px;\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_left_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover, QScrollBar::sub-line:horizontal:on {\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_left.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: left;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"  margin: 3px 0px 3px 0px;\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_up_disabled.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover, QScrollBar::sub-line:vertical:on {\n"
"  border-image: url(\":/qss_icons/dark/rc/arrow_up.png\");\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  subcontrol-position: top;\n"
"  subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"  background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"  background: none;\n"
"}\n"
"\n"
"/* QTextEdit --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-specific-widgets\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTextEdit {\n"
"  background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"  border-radius: 4px;\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QTextEdit:selected {\n"
"  background: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"/* QPlainTextEdit ---------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QPlainTextEdit {\n"
"  background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"  border-radius: 4px;\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QPlainTextEdit:selected {\n"
"  background: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"/* QSizeGrip --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qsizegrip\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QSizeGrip {\n"
"  background: transparent;\n"
"  width: 12px;\n"
"  height: 12px;\n"
"  image: url(\":/qss_icons/dark/rc/window_grip.png\");\n"
"}\n"
"\n"
"/* QStackedWidget ---------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QStackedWidget {\n"
"  padding: 2px;\n"
"  border: 1px solid #455364;\n"
"  border: 1px solid #19232D;\n"
"}\n"
"\n"
"/* QToolBar ---------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtoolbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolBar {\n"
"  background-color: #455364;\n"
"  border-bottom: 1px solid #19232D;\n"
"  padding: 1px;\n"
"  font-weight: bold;\n"
"  spacing: 2px;\n"
"}\n"
"\n"
"QToolBar:disabled {\n"
"  /* Fixes #272 */\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QToolBar::handle:horizontal {\n"
"  width: 16px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_move_horizontal.png\");\n"
"}\n"
"\n"
"QToolBar::handle:vertical {\n"
"  height: 16px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_move_vertical.png\");\n"
"}\n"
"\n"
"QToolBar::separator:horizontal {\n"
"  width: 16px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_separator_horizontal.png\");\n"
"}\n"
"\n"
"QToolBar::separator:vertical {\n"
"  height: 16px;\n"
"  image: url(\":/qss_icons/dark/rc/toolbar_separator_vertical.png\");\n"
"}\n"
"\n"
"QToolButton#qt_toolbar_ext_button {\n"
"  background: #455364;\n"
"  border: 0px;\n"
"  color: #E0E1E3;\n"
"  image: url(\":/qss_icons/dark/rc/arrow_right.png\");\n"
"}\n"
"\n"
"/* QAbstractSpinBox -------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractSpinBox {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #E0E1E3;\n"
"  /* This fixes 103, 111 */\n"
"  padding-top: 2px;\n"
"  /* This fixes 103, 111 */\n"
"  padding-bottom: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-radius: 4px;\n"
"  /* min-width: 5px; removed to fix 109 */\n"
"}\n"
"\n"
"QAbstractSpinBox:up-button {\n"
"  background-color: transparent #19232D;\n"
"  subcontrol-origin: border;\n"
"  subcontrol-position: top right;\n"
"  border-left: 1px solid #455364;\n"
"  border-bottom: 1px solid #455364;\n"
"  border-top-left-radius: 0;\n"
"  border-bottom-left-radius: 0;\n"
"  margin: 1px;\n"
"  width: 12px;\n"
"  margin-bottom: -1px;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow, QAbstractSpinBox::up-arrow:disabled, QAbstractSpinBox::up-arrow:off {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_up_disabled.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QAbstractSpinBox::up-arrow:hover {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_up.png\");\n"
"}\n"
"\n"
"QAbstractSpinBox:down-button {\n"
"  background-color: transparent #19232D;\n"
"  subcontrol-origin: border;\n"
"  subcontrol-position: bottom right;\n"
"  border-left: 1px solid #455364;\n"
"  border-top: 1px solid #455364;\n"
"  border-top-left-radius: 0;\n"
"  border-bottom-left-radius: 0;\n"
"  margin: 1px;\n"
"  width: 12px;\n"
"  margin-top: -1px;\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow, QAbstractSpinBox::down-arrow:disabled, QAbstractSpinBox::down-arrow:off {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down_disabled.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QAbstractSpinBox::down-arrow:hover {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"}\n"
"\n"
"QAbstractSpinBox:hover {\n"
"  border: 1px solid #346792;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QAbstractSpinBox:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QAbstractSpinBox:selected {\n"
"  background: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------------ */\n"
"/* DISPLAYS --------------------------------------------------------------- */\n"
"/* ------------------------------------------------------------------------ */\n"
"/* QLabel -----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qframe\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QLabel {\n"
"  background-color: #19232D;\n"
"  border: 0px solid #455364;\n"
"  padding: 2px;\n"
"  margin: 0px;\n"
"  color: #E0E1E3;\n"
"  font-size: 20px;\n"
"}\n"
"\n"
"QLabel:disabled {\n"
"  background-color: #19232D;\n"
"  border: 0px solid #455364;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"/* QTextBrowser -----------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qabstractscrollarea\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTextBrowser {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #E0E1E3;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTextBrowser:disabled {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTextBrowser:hover, QTextBrowser:!hover, QTextBrowser:selected, QTextBrowser:pressed {\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"/* QGraphicsView ----------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QGraphicsView {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #E0E1E3;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QGraphicsView:disabled {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QGraphicsView:hover, QGraphicsView:!hover, QGraphicsView:selected, QGraphicsView:pressed {\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"/* QCalendarWidget --------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QCalendarWidget {\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QCalendarWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"/* QLCDNumber -------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QLCDNumber {\n"
"  background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QLCDNumber:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"/* QProgressBar -----------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qprogressbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QProgressBar {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #E0E1E3;\n"
"  border-radius: 4px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar:disabled {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"  background-color: #346792;\n"
"  color: #19232D;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QProgressBar::chunk:disabled {\n"
"  background-color: #26486B;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------------ */\n"
"/* BUTTONS ---------------------------------------------------------------- */\n"
"/* ------------------------------------------------------------------------ */\n"
"/* QPushButton ------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qpushbutton\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QPushButton {\n"
"  background-color: #455364;\n"
"  color: #E0E1E3;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"  border: none;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"  background-color: #455364;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"  background-color: #60798B;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QPushButton:checked:disabled {\n"
"  background-color: #60798B;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QPushButton:checked:selected {\n"
"  background: #60798B;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #54687A;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: #60798B;\n"
"}\n"
"\n"
"QPushButton:selected {\n"
"  background: #60798B;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QPushButton::menu-indicator {\n"
"  subcontrol-origin: padding;\n"
"  subcontrol-position: bottom right;\n"
"  bottom: 4px;\n"
"}\n"
"\n"
"QDialogButtonBox QPushButton {\n"
"  /* Issue #194 #248 - Special case of QPushButton inside dialogs, for better UI */\n"
"  min-width: 80px;\n"
"}\n"
"\n"
"/* QToolButton ------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtoolbutton\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolButton {\n"
"  background-color: #455364;\n"
"  color: #E0E1E3;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"  border: none;\n"
"  /* The subcontrols below are used only in the DelayedPopup mode */\n"
"  /* The subcontrols below are used only in the MenuButtonPopup mode */\n"
"  /* The subcontrol below is used only in the InstantPopup or DelayedPopup mode */\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"  background-color: #455364;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"}\n"
"\n"
"QToolButton:checked {\n"
"  background-color: #60798B;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QToolButton:checked:disabled {\n"
"  background-color: #60798B;\n"
"  color: #9DA9B5;\n"
"  border-radius: 4px;\n"
"  padding: 2px;\n"
"  outline: none;\n"
"}\n"
"\n"
"QToolButton:checked:hover {\n"
"  background-color: #54687A;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QToolButton:checked:pressed {\n"
"  background-color: #60798B;\n"
"}\n"
"\n"
"QToolButton:checked:selected {\n"
"  background: #60798B;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"  background-color: #54687A;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"  background-color: #60798B;\n"
"}\n"
"\n"
"QToolButton:selected {\n"
"  background: #60798B;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"0\"] {\n"
"  /* Only for DelayedPopup */\n"
"  padding-right: 2px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"] {\n"
"  /* Only for MenuButtonPopup */\n"
"  padding-right: 20px;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"]::menu-button {\n"
"  border: none;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"1\"]::menu-button:hover {\n"
"  border: none;\n"
"  border-left: 1px solid #455364;\n"
"  border-radius: 0;\n"
"}\n"
"\n"
"QToolButton[popupMode=\"2\"] {\n"
"  /* Only for InstantPopup */\n"
"  padding-right: 2px;\n"
"}\n"
"\n"
"QToolButton::menu-button {\n"
"  padding: 2px;\n"
"  border-radius: 4px;\n"
"  width: 12px;\n"
"  border: none;\n"
"  outline: none;\n"
"}\n"
"\n"
"QToolButton::menu-button:hover {\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QToolButton::menu-button:checked:hover {\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"  top: 0;\n"
"  /* Exclude a shift for better image */\n"
"  left: -2px;\n"
"  /* Shift it a bit */\n"
"}\n"
"\n"
"QToolButton::menu-arrow {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QToolButton::menu-arrow:hover {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down_focus.png\");\n"
"}\n"
"\n"
"/* QCommandLinkButton -----------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QCommandLinkButton {\n"
"  background-color: transparent;\n"
"  border: 1px solid #455364;\n"
"  color: #E0E1E3;\n"
"  border-radius: 4px;\n"
"  padding: 0px;\n"
"  margin: 0px;\n"
"}\n"
"\n"
"QCommandLinkButton:disabled {\n"
"  background-color: transparent;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"/* ------------------------------------------------------------------------ */\n"
"/* INPUTS - NO FIELDS ----------------------------------------------------- */\n"
"/* ------------------------------------------------------------------------ */\n"
"/* QComboBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qcombobox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QComboBox {\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  selection-background-color: #346792;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  /* padding-right = 36; 4 + 16*2 See scrollbar size */\n"
"  /* changed to 4px to fix #239 */\n"
"  /* Fixes #103, #111 */\n"
"  min-height: 1.5em;\n"
"  /* padding-top: 2px;     removed to fix #132 */\n"
"  /* padding-bottom: 2px;  removed to fix #132 */\n"
"  /* min-width: 75px;      removed to fix #109 */\n"
"  /* Needed to remove indicator - fix #132 */\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"  border: 1px solid #455364;\n"
"  border-radius: 0;\n"
"  background-color: #19232D;\n"
"  selection-background-color: #346792;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView:hover {\n"
"  background-color: #19232D;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView:selected {\n"
"  background: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView:alternate {\n"
"  background: #19232D;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"  selection-background-color: #346792;\n"
"}\n"
"\n"
"QComboBox::indicator {\n"
"  border: none;\n"
"  border-radius: 0;\n"
"  background-color: transparent;\n"
"  selection-background-color: transparent;\n"
"  color: transparent;\n"
"  selection-color: transparent;\n"
"  /* Needed to remove indicator - fix #132 */\n"
"}\n"
"\n"
"QComboBox::indicator:alternate {\n"
"  background: #19232D;\n"
"}\n"
"\n"
"QComboBox::item {\n"
"  /* Remove to fix #282, #285 and MR #288*/\n"
"  /*&:checked {\n"
"            font-weight: bold;\n"
"        }\n"
"\n"
"        &:selected {\n"
"            border: 0px solid transparent;\n"
"        }\n"
"        */\n"
"}\n"
"\n"
"QComboBox::item:alternate {\n"
"  background: #19232D;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"  subcontrol-origin: padding;\n"
"  subcontrol-position: top right;\n"
"  width: 12px;\n"
"  border-left: 1px solid #455364;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down_disabled.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on, QComboBox::down-arrow:hover, QComboBox::down-arrow:focus {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"}\n"
"\n"
"/* QSlider ----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qslider\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QSlider:disabled {\n"
"  background: #19232D;\n"
"}\n"
"\n"
"QSlider:focus {\n"
"  border: none;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"  background: #455364;\n"
"  border: 1px solid #455364;\n"
"  height: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"  background: #455364;\n"
"  border: 1px solid #455364;\n"
"  width: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"  background: #346792;\n"
"  border: 1px solid #455364;\n"
"  width: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical :disabled {\n"
"  background: #26486B;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"  background: #346792;\n"
"  border: 1px solid #455364;\n"
"  height: 4px;\n"
"  margin: 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"  background: #26486B;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"  background: #9DA9B5;\n"
"  border: 1px solid #455364;\n"
"  width: 8px;\n"
"  height: 8px;\n"
"  margin: -8px 0px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"  background: #346792;\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"  background: #9DA9B5;\n"
"  border: 1px solid #455364;\n"
"  width: 8px;\n"
"  height: 8px;\n"
"  margin: 0 -8px;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover {\n"
"  background: #346792;\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QSlider::handle:vertical:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"/* QLineEdit --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qlineedit\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QLineEdit {\n"
"  background-color: #19232D;\n"
"  padding-top: 2px;\n"
"  /* This QLineEdit fix  103, 111 */\n"
"  padding-bottom: 2px;\n"
"  /* This QLineEdit fix  103, 111 */\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-style: solid;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"  border: 1px solid #346792;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QLineEdit:selected {\n"
"  background-color: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"/* QTabWiget --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtabwidget-and-qtabbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTabWidget {\n"
"  padding: 2px;\n"
"  selection-background-color: #455364;\n"
"}\n"
"\n"
"QTabWidget QWidget {\n"
"  /* Fixes #189 */\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  margin: 0px;\n"
"  /* Fixes double border inside pane with pyqt5 */\n"
"  padding: 0px;\n"
"}\n"
"\n"
"QTabWidget::pane:selected {\n"
"  background-color: #455364;\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"/* QTabBar ----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtabwidget-and-qtabbar\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTabBar, QDockWidget QTabBar {\n"
"  qproperty-drawBase: 0;\n"
"  border-radius: 4px;\n"
"  margin: 0px;\n"
"  padding: 2px;\n"
"  border: 0;\n"
"  /* left: 5px; move to the right by 5px - removed for fix */\n"
"}\n"
"\n"
"QTabBar::close-button, QDockWidget QTabBar::close-button {\n"
"  border: 0;\n"
"  margin: 0;\n"
"  padding: 4px;\n"
"  image: url(\":/qss_icons/dark/rc/window_close.png\");\n"
"}\n"
"\n"
"QTabBar::close-button:hover, QDockWidget QTabBar::close-button:hover {\n"
"  image: url(\":/qss_icons/dark/rc/window_close_focus.png\");\n"
"}\n"
"\n"
"QTabBar::close-button:pressed, QDockWidget QTabBar::close-button:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/window_close_pressed.png\");\n"
"}\n"
"\n"
"QTabBar::tab, QDockWidget QTabBar::tab {\n"
"  /* !selected and disabled ----------------------------------------- */\n"
"  /* selected ------------------------------------------------------- */\n"
"}\n"
"\n"
"QTabBar::tab:top:selected:disabled, QDockWidget QTabBar::tab:top:selected:disabled {\n"
"  border-bottom: 3px solid #26486B;\n"
"  color: #9DA9B5;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected:disabled, QDockWidget QTabBar::tab:bottom:selected:disabled {\n"
"  border-top: 3px solid #26486B;\n"
"  color: #9DA9B5;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected:disabled, QDockWidget QTabBar::tab:left:selected:disabled {\n"
"  border-right: 3px solid #26486B;\n"
"  color: #9DA9B5;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected:disabled, QDockWidget QTabBar::tab:right:selected:disabled {\n"
"  border-left: 3px solid #26486B;\n"
"  color: #9DA9B5;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:disabled, QDockWidget QTabBar::tab:top:!selected:disabled {\n"
"  border-bottom: 3px solid #19232D;\n"
"  color: #9DA9B5;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:disabled, QDockWidget QTabBar::tab:bottom:!selected:disabled {\n"
"  border-top: 3px solid #19232D;\n"
"  color: #9DA9B5;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:disabled, QDockWidget QTabBar::tab:left:!selected:disabled {\n"
"  border-right: 3px solid #19232D;\n"
"  color: #9DA9B5;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected:disabled, QDockWidget QTabBar::tab:right:!selected:disabled {\n"
"  border-left: 3px solid #19232D;\n"
"  color: #9DA9B5;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected, QDockWidget QTabBar::tab:top:!selected {\n"
"  border-bottom: 2px solid #19232D;\n"
"  margin-top: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected, QDockWidget QTabBar::tab:bottom:!selected {\n"
"  border-top: 2px solid #19232D;\n"
"  margin-bottom: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected, QDockWidget QTabBar::tab:left:!selected {\n"
"  border-left: 2px solid #19232D;\n"
"  margin-right: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected, QDockWidget QTabBar::tab:right:!selected {\n"
"  border-right: 2px solid #19232D;\n"
"  margin-left: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:top, QDockWidget QTabBar::tab:top {\n"
"  background-color: #455364;\n"
"  margin-left: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  padding-top: 2px;\n"
"  padding-bottom: 2px;\n"
"  min-width: 5px;\n"
"  border-bottom: 3px solid #455364;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected, QDockWidget QTabBar::tab:top:selected {\n"
"  background-color: #54687A;\n"
"  border-bottom: 3px solid #259AE9;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:top:!selected:hover, QDockWidget QTabBar::tab:top:!selected:hover {\n"
"  border: 1px solid #1A72BB;\n"
"  border-bottom: 3px solid #1A72BB;\n"
"  /* Fixes spyder-ide/spyder#9766 and #243 */\n"
"  padding-left: 3px;\n"
"  padding-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom, QDockWidget QTabBar::tab:bottom {\n"
"  border-top: 3px solid #455364;\n"
"  background-color: #455364;\n"
"  margin-left: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  padding-top: 2px;\n"
"  padding-bottom: 2px;\n"
"  border-bottom-left-radius: 4px;\n"
"  border-bottom-right-radius: 4px;\n"
"  min-width: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:selected, QDockWidget QTabBar::tab:bottom:selected {\n"
"  background-color: #54687A;\n"
"  border-top: 3px solid #259AE9;\n"
"  border-bottom-left-radius: 4px;\n"
"  border-bottom-right-radius: 4px;\n"
"}\n"
"\n"
"QTabBar::tab:bottom:!selected:hover, QDockWidget QTabBar::tab:bottom:!selected:hover {\n"
"  border: 1px solid #1A72BB;\n"
"  border-top: 3px solid #1A72BB;\n"
"  /* Fixes spyder-ide/spyder#9766 and #243 */\n"
"  padding-left: 3px;\n"
"  padding-right: 3px;\n"
"}\n"
"\n"
"QTabBar::tab:left, QDockWidget QTabBar::tab:left {\n"
"  background-color: #455364;\n"
"  margin-top: 2px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"  border-top-left-radius: 4px;\n"
"  border-bottom-left-radius: 4px;\n"
"  min-height: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:left:selected, QDockWidget QTabBar::tab:left:selected {\n"
"  background-color: #54687A;\n"
"  border-right: 3px solid #259AE9;\n"
"}\n"
"\n"
"QTabBar::tab:left:!selected:hover, QDockWidget QTabBar::tab:left:!selected:hover {\n"
"  border: 1px solid #1A72BB;\n"
"  border-right: 3px solid #1A72BB;\n"
"  /* Fixes different behavior #271 */\n"
"  margin-right: 0px;\n"
"  padding-right: -1px;\n"
"}\n"
"\n"
"QTabBar::tab:right, QDockWidget QTabBar::tab:right {\n"
"  background-color: #455364;\n"
"  margin-top: 2px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  padding-top: 4px;\n"
"  padding-bottom: 4px;\n"
"  border-top-right-radius: 4px;\n"
"  border-bottom-right-radius: 4px;\n"
"  min-height: 5px;\n"
"}\n"
"\n"
"QTabBar::tab:right:selected, QDockWidget QTabBar::tab:right:selected {\n"
"  background-color: #54687A;\n"
"  border-left: 3px solid #259AE9;\n"
"}\n"
"\n"
"QTabBar::tab:right:!selected:hover, QDockWidget QTabBar::tab:right:!selected:hover {\n"
"  border: 1px solid #1A72BB;\n"
"  border-left: 3px solid #1A72BB;\n"
"  /* Fixes different behavior #271 */\n"
"  margin-left: 0px;\n"
"  padding-left: 0px;\n"
"}\n"
"\n"
"QTabBar QToolButton, QDockWidget QTabBar QToolButton {\n"
"  /* Fixes #136 */\n"
"  background-color: #455364;\n"
"  height: 12px;\n"
"  width: 12px;\n"
"}\n"
"\n"
"QTabBar QToolButton:pressed, QDockWidget QTabBar QToolButton:pressed {\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QTabBar QToolButton:pressed:hover, QDockWidget QTabBar QToolButton:pressed:hover {\n"
"  border: 1px solid #346792;\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:enabled, QDockWidget QTabBar QToolButton::left-arrow:enabled {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_left.png\");\n"
"}\n"
"\n"
"QTabBar QToolButton::left-arrow:disabled, QDockWidget QTabBar QToolButton::left-arrow:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_left_disabled.png\");\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:enabled, QDockWidget QTabBar QToolButton::right-arrow:enabled {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_right.png\");\n"
"}\n"
"\n"
"QTabBar QToolButton::right-arrow:disabled, QDockWidget QTabBar QToolButton::right-arrow:disabled {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_right_disabled.png\");\n"
"}\n"
"\n"
"/* QDockWiget -------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QDockWidget {\n"
"  outline: 1px solid #455364;\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  titlebar-close-icon: url(\":/qss_icons/dark/rc/transparent.png\");\n"
"  titlebar-normal-icon: url(\":/qss_icons/dark/rc/transparent.png\");\n"
"}\n"
"\n"
"QDockWidget::title {\n"
"  /* Better size for title bar */\n"
"  padding: 3px;\n"
"  spacing: 4px;\n"
"  border: none;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"QDockWidget::close-button {\n"
"  icon-size: 12px;\n"
"  border: none;\n"
"  background: transparent;\n"
"  background-image: transparent;\n"
"  border: 0;\n"
"  margin: 0;\n"
"  padding: 0;\n"
"  image: url(\":/qss_icons/dark/rc/window_close.png\");\n"
"}\n"
"\n"
"QDockWidget::close-button:hover {\n"
"  image: url(\":/qss_icons/dark/rc/window_close_focus.png\");\n"
"}\n"
"\n"
"QDockWidget::close-button:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/window_close_pressed.png\");\n"
"}\n"
"\n"
"QDockWidget::float-button {\n"
"  icon-size: 12px;\n"
"  border: none;\n"
"  background: transparent;\n"
"  background-image: transparent;\n"
"  border: 0;\n"
"  margin: 0;\n"
"  padding: 0;\n"
"  image: url(\":/qss_icons/dark/rc/window_undock.png\");\n"
"}\n"
"\n"
"QDockWidget::float-button:hover {\n"
"  image: url(\":/qss_icons/dark/rc/window_undock_focus.png\");\n"
"}\n"
"\n"
"QDockWidget::float-button:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/window_undock_pressed.png\");\n"
"}\n"
"\n"
"/* QTreeView QListView QTableView -----------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtreeview\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qlistview\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtableview\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QTreeView:branch:selected, QTreeView:branch:hover {\n"
"  background: url(\":/qss_icons/dark/rc/transparent.png\");\n"
"}\n"
"\n"
"QTreeView:branch:has-siblings:!adjoins-item {\n"
"  border-image: url(\":/qss_icons/dark/rc/branch_line.png\") 0;\n"
"}\n"
"\n"
"QTreeView:branch:has-siblings:adjoins-item {\n"
"  border-image: url(\":/qss_icons/dark/rc/branch_more.png\") 0;\n"
"}\n"
"\n"
"QTreeView:branch:!has-children:!has-siblings:adjoins-item {\n"
"  border-image: url(\":/qss_icons/dark/rc/branch_end.png\") 0;\n"
"}\n"
"\n"
"QTreeView:branch:has-children:!has-siblings:closed, QTreeView:branch:closed:has-children:has-siblings {\n"
"  border-image: none;\n"
"  image: url(\":/qss_icons/dark/rc/branch_closed.png\");\n"
"}\n"
"\n"
"QTreeView:branch:open:has-children:!has-siblings, QTreeView:branch:open:has-children:has-siblings {\n"
"  border-image: none;\n"
"  image: url(\":/qss_icons/dark/rc/branch_open.png\");\n"
"}\n"
"\n"
"QTreeView:branch:has-children:!has-siblings:closed:hover, QTreeView:branch:closed:has-children:has-siblings:hover {\n"
"  image: url(\":/qss_icons/dark/rc/branch_closed_focus.png\");\n"
"}\n"
"\n"
"QTreeView:branch:open:has-children:!has-siblings:hover, QTreeView:branch:open:has-children:has-siblings:hover {\n"
"  image: url(\":/qss_icons/dark/rc/branch_open_focus.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:checked,\n"
"QListView::indicator:checked,\n"
"QTableView::indicator:checked,\n"
"QColumnView::indicator:checked {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:checked:hover, QTreeView::indicator:checked:focus, QTreeView::indicator:checked:pressed,\n"
"QListView::indicator:checked:hover,\n"
"QListView::indicator:checked:focus,\n"
"QListView::indicator:checked:pressed,\n"
"QTableView::indicator:checked:hover,\n"
"QTableView::indicator:checked:focus,\n"
"QTableView::indicator:checked:pressed,\n"
"QColumnView::indicator:checked:hover,\n"
"QColumnView::indicator:checked:focus,\n"
"QColumnView::indicator:checked:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_checked_focus.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked,\n"
"QListView::indicator:unchecked,\n"
"QTableView::indicator:unchecked,\n"
"QColumnView::indicator:unchecked {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:unchecked:hover, QTreeView::indicator:unchecked:focus, QTreeView::indicator:unchecked:pressed,\n"
"QListView::indicator:unchecked:hover,\n"
"QListView::indicator:unchecked:focus,\n"
"QListView::indicator:unchecked:pressed,\n"
"QTableView::indicator:unchecked:hover,\n"
"QTableView::indicator:unchecked:focus,\n"
"QTableView::indicator:unchecked:pressed,\n"
"QColumnView::indicator:unchecked:hover,\n"
"QColumnView::indicator:unchecked:focus,\n"
"QColumnView::indicator:unchecked:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_unchecked_focus.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:indeterminate,\n"
"QListView::indicator:indeterminate,\n"
"QTableView::indicator:indeterminate,\n"
"QColumnView::indicator:indeterminate {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate.png\");\n"
"}\n"
"\n"
"QTreeView::indicator:indeterminate:hover, QTreeView::indicator:indeterminate:focus, QTreeView::indicator:indeterminate:pressed,\n"
"QListView::indicator:indeterminate:hover,\n"
"QListView::indicator:indeterminate:focus,\n"
"QListView::indicator:indeterminate:pressed,\n"
"QTableView::indicator:indeterminate:hover,\n"
"QTableView::indicator:indeterminate:focus,\n"
"QTableView::indicator:indeterminate:pressed,\n"
"QColumnView::indicator:indeterminate:hover,\n"
"QColumnView::indicator:indeterminate:focus,\n"
"QColumnView::indicator:indeterminate:pressed {\n"
"  image: url(\":/qss_icons/dark/rc/checkbox_indeterminate_focus.png\");\n"
"}\n"
"\n"
"QTreeView,\n"
"QListView,\n"
"QTableView,\n"
"QColumnView {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #E0E1E3;\n"
"  gridline-color: #455364;\n"
"  border-radius: 4px;\n"
"}\n"
"\n"
"QTreeView:disabled,\n"
"QListView:disabled,\n"
"QTableView:disabled,\n"
"QColumnView:disabled {\n"
"  background-color: #19232D;\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QTreeView:selected,\n"
"QListView:selected,\n"
"QTableView:selected,\n"
"QColumnView:selected {\n"
"  background-color: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"QTreeView:focus,\n"
"QListView:focus,\n"
"QTableView:focus,\n"
"QColumnView:focus {\n"
"  border: 1px solid #1A72BB;\n"
"}\n"
"\n"
"QTreeView::item:pressed,\n"
"QListView::item:pressed,\n"
"QTableView::item:pressed,\n"
"QColumnView::item:pressed {\n"
"  background-color: #346792;\n"
"}\n"
"\n"
"QTreeView::item:selected:active,\n"
"QListView::item:selected:active,\n"
"QTableView::item:selected:active,\n"
"QColumnView::item:selected:active {\n"
"  background-color: #346792;\n"
"}\n"
"\n"
"QTreeView::item:selected:!active,\n"
"QListView::item:selected:!active,\n"
"QTableView::item:selected:!active,\n"
"QColumnView::item:selected:!active {\n"
"  color: #E0E1E3;\n"
"  background-color: #37414F;\n"
"}\n"
"\n"
"QTreeView::item:!selected:hover,\n"
"QListView::item:!selected:hover,\n"
"QTableView::item:!selected:hover,\n"
"QColumnView::item:!selected:hover {\n"
"  outline: 0;\n"
"  color: #E0E1E3;\n"
"  background-color: #37414F;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"  background-color: #19232D;\n"
"  border: 1px transparent #455364;\n"
"  border-radius: 0px;\n"
"}\n"
"\n"
"/* QHeaderView ------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qheaderview\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QHeaderView {\n"
"  background-color: #455364;\n"
"  border: 0px transparent #455364;\n"
"  padding: 0;\n"
"  margin: 0;\n"
"  border-radius: 0;\n"
"}\n"
"\n"
"QHeaderView:disabled {\n"
"  background-color: #455364;\n"
"  border: 1px transparent #455364;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"  background-color: #455364;\n"
"  color: #E0E1E3;\n"
"  border-radius: 0;\n"
"  text-align: left;\n"
"  font-size: 13px;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal {\n"
"  padding-top: 0;\n"
"  padding-bottom: 0;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-left: 1px solid #19232D;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal::first, QHeaderView::section::horizontal::only-one {\n"
"  border-left: 1px solid #455364;\n"
"}\n"
"\n"
"QHeaderView::section::horizontal:disabled {\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QHeaderView::section::vertical {\n"
"  padding-top: 0;\n"
"  padding-bottom: 0;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  border-top: 1px solid #19232D;\n"
"}\n"
"\n"
"QHeaderView::section::vertical::first, QHeaderView::section::vertical::only-one {\n"
"  border-top: 1px solid #455364;\n"
"}\n"
"\n"
"QHeaderView::section::vertical:disabled {\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QHeaderView::down-arrow {\n"
"  /* Those settings (border/width/height/background-color) solve bug */\n"
"  /* transparent arrow background and size */\n"
"  background-color: #455364;\n"
"  border: none;\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"}\n"
"\n"
"QHeaderView::up-arrow {\n"
"  background-color: #455364;\n"
"  border: none;\n"
"  height: 12px;\n"
"  width: 12px;\n"
"  padding-left: 2px;\n"
"  padding-right: 2px;\n"
"  image: url(\":/qss_icons/dark/rc/arrow_up.png\");\n"
"}\n"
"\n"
"/* QToolBox --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qtoolbox\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QToolBox {\n"
"  padding: 0px;\n"
"  border: 0px;\n"
"  border: 1px solid #455364;\n"
"}\n"
"\n"
"QToolBox:selected {\n"
"  padding: 0px;\n"
"  border: 2px solid #346792;\n"
"}\n"
"\n"
"QToolBox::tab {\n"
"  background-color: #19232D;\n"
"  border: 1px solid #455364;\n"
"  color: #E0E1E3;\n"
"  border-top-left-radius: 4px;\n"
"  border-top-right-radius: 4px;\n"
"}\n"
"\n"
"QToolBox::tab:disabled {\n"
"  color: #9DA9B5;\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"  background-color: #60798B;\n"
"  border-bottom: 2px solid #346792;\n"
"}\n"
"\n"
"QToolBox::tab:selected:disabled {\n"
"  background-color: #455364;\n"
"  border-bottom: 2px solid #26486B;\n"
"}\n"
"\n"
"QToolBox::tab:!selected {\n"
"  background-color: #455364;\n"
"  border-bottom: 2px solid #455364;\n"
"}\n"
"\n"
"QToolBox::tab:!selected:disabled {\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"QToolBox::tab:hover {\n"
"  border-color: #1A72BB;\n"
"  border-bottom: 2px solid #1A72BB;\n"
"}\n"
"\n"
"QToolBox QScrollArea QWidget QWidget {\n"
"  padding: 0px;\n"
"  border: 0px;\n"
"  background-color: #19232D;\n"
"}\n"
"\n"
"/* QFrame -----------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qframe\n"
"https://doc.qt.io/qt-5/qframe.html#-prop\n"
"https://doc.qt.io/qt-5/qframe.html#details\n"
"https://stackoverflow.com/questions/14581498/qt-stylesheet-for-hline-vline-color\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"/* (dot) .QFrame  fix #141, #126, #123 */\n"
".QFrame {\n"
"  border-radius: 4px;\n"
"  border: 1px solid #455364;\n"
"  /* No frame */\n"
"  /* HLine */\n"
"  /* HLine */\n"
"}\n"
"\n"
".QFrame[frameShape=\"0\"] {\n"
"  border-radius: 4px;\n"
"  border: 1px transparent #455364;\n"
"}\n"
"\n"
".QFrame[frameShape=\"4\"] {\n"
"  max-height: 2px;\n"
"  border: none;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
".QFrame[frameShape=\"5\"] {\n"
"  max-width: 2px;\n"
"  border: none;\n"
"  background-color: #455364;\n"
"}\n"
"\n"
"/* QSplitter --------------------------------------------------------------\n"
"\n"
"https://doc.qt.io/qt-5/stylesheet-examples.html#customizing-qsplitter\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QSplitter {\n"
"  background-color: #455364;\n"
"  spacing: 0px;\n"
"  padding: 0px;\n"
"  margin: 0px;\n"
"}\n"
"\n"
"QSplitter::handle {\n"
"  background-color: #455364;\n"
"  border: 0px solid #19232D;\n"
"  spacing: 0px;\n"
"  padding: 1px;\n"
"  margin: 0px;\n"
"}\n"
"\n"
"QSplitter::handle:hover {\n"
"  background-color: #9DA9B5;\n"
"}\n"
"\n"
"QSplitter::handle:horizontal {\n"
"  width: 5px;\n"
"  image: url(\":/qss_icons/dark/rc/line_vertical.png\");\n"
"}\n"
"\n"
"QSplitter::handle:vertical {\n"
"  height: 5px;\n"
"  image: url(\":/qss_icons/dark/rc/line_horizontal.png\");\n"
"}\n"
"\n"
"/* QDateEdit, QDateTimeEdit -----------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QDateEdit, QDateTimeEdit {\n"
"  selection-background-color: #346792;\n"
"  border-style: solid;\n"
"  border: 1px solid #455364;\n"
"  border-radius: 4px;\n"
"  /* This fixes 103, 111 */\n"
"  padding-top: 2px;\n"
"  /* This fixes 103, 111 */\n"
"  padding-bottom: 2px;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px;\n"
"  min-width: 10px;\n"
"}\n"
"\n"
"QDateEdit:on, QDateTimeEdit:on {\n"
"  selection-background-color: #346792;\n"
"}\n"
"\n"
"QDateEdit::drop-down, QDateTimeEdit::drop-down {\n"
"  subcontrol-origin: padding;\n"
"  subcontrol-position: top right;\n"
"  width: 12px;\n"
"  border-left: 1px solid #455364;\n"
"}\n"
"\n"
"QDateEdit::down-arrow, QDateTimeEdit::down-arrow {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down_disabled.png\");\n"
"  height: 8px;\n"
"  width: 8px;\n"
"}\n"
"\n"
"QDateEdit::down-arrow:on, QDateEdit::down-arrow:hover, QDateEdit::down-arrow:focus, QDateTimeEdit::down-arrow:on, QDateTimeEdit::down-arrow:hover, QDateTimeEdit::down-arrow:focus {\n"
"  image: url(\":/qss_icons/dark/rc/arrow_down.png\");\n"
"}\n"
"\n"
"QDateEdit QAbstractItemView, QDateTimeEdit QAbstractItemView {\n"
"  background-color: #19232D;\n"
"  border-radius: 4px;\n"
"  border: 1px solid #455364;\n"
"  selection-background-color: #346792;\n"
"}\n"
"\n"
"/* QAbstractView ----------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"QAbstractView:hover {\n"
"  border: 1px solid #346792;\n"
"  color: #E0E1E3;\n"
"}\n"
"\n"
"QAbstractView:selected {\n"
"  background: #346792;\n"
"  color: #455364;\n"
"}\n"
"\n"
"/* PlotWidget -------------------------------------------------------------\n"
"\n"
"--------------------------------------------------------------------------- */\n"
"PlotWidget {\n"
"  /* Fix cut labels in plots #134 */\n"
"  padding: 0px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Veri_Tabani_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.details_groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.details_groupBox_2.setMaximumSize(QtCore.QSize(560, 330))
        self.details_groupBox_2.setStyleSheet("")
        self.details_groupBox_2.setObjectName("details_groupBox_2")
        self.Goster_pushButton = QtWidgets.QPushButton(self.details_groupBox_2)
        self.Goster_pushButton.setGeometry(QtCore.QRect(40, 240, 130, 50))
        self.Goster_pushButton.setStyleSheet("")
        self.Goster_pushButton.setObjectName("Goster_pushButton")
        self.Temiz_pushButton = QtWidgets.QPushButton(self.details_groupBox_2)
        self.Temiz_pushButton.setGeometry(QtCore.QRect(200, 240, 130, 50))
        self.Temiz_pushButton.setStyleSheet("")
        self.Temiz_pushButton.setObjectName("Temiz_pushButton")
        self.Leke_radioButton = QtWidgets.QRadioButton(self.details_groupBox_2)
        self.Leke_radioButton.setGeometry(QtCore.QRect(40, 70, 91, 31))
        self.Leke_radioButton.setObjectName("Leke_radioButton")
        self.Delik_RadioButton = QtWidgets.QRadioButton(self.details_groupBox_2)
        self.Delik_RadioButton.setGeometry(QtCore.QRect(200, 70, 91, 31))
        self.Delik_RadioButton.setObjectName("Delik_RadioButton")
        self.Iplik_RadioButton = QtWidgets.QRadioButton(self.details_groupBox_2)
        self.Iplik_RadioButton.setGeometry(QtCore.QRect(40, 110, 91, 31))
        self.Iplik_RadioButton.setObjectName("Iplik_RadioButton")
        self.Yag_RadioButton = QtWidgets.QRadioButton(self.details_groupBox_2)
        self.Yag_RadioButton.setGeometry(QtCore.QRect(200, 110, 91, 31))
        self.Yag_RadioButton.setObjectName("Yag_RadioButton")
        self.Yatay_RadioButton = QtWidgets.QRadioButton(self.details_groupBox_2)
        self.Yatay_RadioButton.setGeometry(QtCore.QRect(40, 150, 91, 31))
        self.Yatay_RadioButton.setObjectName("Yatay_RadioButton")
        self.Dikey_RadioButton = QtWidgets.QRadioButton(self.details_groupBox_2)
        self.Dikey_RadioButton.setGeometry(QtCore.QRect(200, 150, 91, 31))
        self.Dikey_RadioButton.setObjectName("Dikey_RadioButton")
        self.Tumu_RadioButton = QtWidgets.QRadioButton(self.details_groupBox_2)
        self.Tumu_RadioButton.setGeometry(QtCore.QRect(40, 190, 91, 31))
        self.Tumu_RadioButton.setObjectName("Tumu_RadioButton")
        self.Kirik_RadioButton = QtWidgets.QRadioButton(self.details_groupBox_2)
        self.Kirik_RadioButton.setGeometry(QtCore.QRect(200, 190, 91, 31))
        self.Kirik_RadioButton.setObjectName("Kirik_RadioButton")
        self.gridLayout.addWidget(self.details_groupBox_2, 0, 0, 1, 1)
        self.details_groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.details_groupBox.setMaximumSize(QtCore.QSize(711, 330))
        self.details_groupBox.setStyleSheet("")
        self.details_groupBox.setObjectName("details_groupBox")
        self.Baslangic_dateEdit = QtWidgets.QDateEdit(self.details_groupBox)
        self.Baslangic_dateEdit.setGeometry(QtCore.QRect(240, 60, 231, 41))
        self.Baslangic_dateEdit.setStyleSheet("")
        self.Baslangic_dateEdit.setObjectName("Baslangic_dateEdit")
        self.Bitis_dateEdit = QtWidgets.QDateEdit(self.details_groupBox)
        self.Bitis_dateEdit.setGeometry(QtCore.QRect(240, 120, 231, 41))
        self.Bitis_dateEdit.setStyleSheet("")
        self.Bitis_dateEdit.setObjectName("Bitis_dateEdit")
        self.label_3 = QtWidgets.QLabel(self.details_groupBox)
        self.label_3.setGeometry(QtCore.QRect(40, 70, 171, 37))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:white;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.details_groupBox)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 171, 37))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.Listele_pushButton = QtWidgets.QPushButton(self.details_groupBox)
        self.Listele_pushButton.setGeometry(QtCore.QRect(510, 60, 161, 80))
        self.Listele_pushButton.setStyleSheet("")
        self.Listele_pushButton.setObjectName("Listele_pushButton")
        self.Raporla_PushButton = QtWidgets.QPushButton(self.details_groupBox)
        self.Raporla_PushButton.setGeometry(QtCore.QRect(510, 210, 161, 80))
        self.Raporla_PushButton.setStyleSheet("")
        self.Raporla_PushButton.setObjectName("Raporla_PushButton")
        self.label_Dok_No = QtWidgets.QLabel(self.details_groupBox)
        self.label_Dok_No.setGeometry(QtCore.QRect(40, 190, 171, 37))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_Dok_No.setFont(font)
        self.label_Dok_No.setStyleSheet("color:white;")
        self.label_Dok_No.setObjectName("label_Dok_No")
        self.Dok_No_LineEdit = QtWidgets.QLineEdit(self.details_groupBox)
        self.Dok_No_LineEdit.setGeometry(QtCore.QRect(240, 190, 230, 40))
        self.Dok_No_LineEdit.setStyleSheet("")
        self.Dok_No_LineEdit.setObjectName("Dok_No_LineEdit")
        self.label_Kalite_No = QtWidgets.QLabel(self.details_groupBox)
        self.label_Kalite_No.setGeometry(QtCore.QRect(40, 250, 171, 37))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_Kalite_No.setFont(font)
        self.label_Kalite_No.setStyleSheet("color:white;")
        self.label_Kalite_No.setObjectName("label_Kalite_No")
        self.Kalite_No_LineEdit = QtWidgets.QLineEdit(self.details_groupBox)
        self.Kalite_No_LineEdit.setGeometry(QtCore.QRect(240, 250, 230, 40))
        self.Kalite_No_LineEdit.setStyleSheet("")
        self.Kalite_No_LineEdit.setObjectName("Kalite_No_LineEdit")
        self.gridLayout.addWidget(self.details_groupBox, 0, 1, 1, 1)
        self.details_groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.details_groupBox_4.setMaximumSize(QtCore.QSize(590, 330))
        self.details_groupBox_4.setStyleSheet("")
        self.details_groupBox_4.setObjectName("details_groupBox_4")
        self.label_9 = QtWidgets.QLabel(self.details_groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(30, 60, 321, 37))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:white;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.details_groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(30, 120, 321, 37))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color:white;")
        self.label_10.setObjectName("label_10")
        self.Hata_Alani_LineEdit = QtWidgets.QLineEdit(self.details_groupBox_4)
        self.Hata_Alani_LineEdit.setGeometry(QtCore.QRect(360, 60, 201, 40))
        self.Hata_Alani_LineEdit.setStyleSheet("")
        self.Hata_Alani_LineEdit.setObjectName("Hata_Alani_LineEdit")
        self.Metre_LineEdit = QtWidgets.QLineEdit(self.details_groupBox_4)
        self.Metre_LineEdit.setGeometry(QtCore.QRect(360, 120, 201, 40))
        self.Metre_LineEdit.setStyleSheet("")
        self.Metre_LineEdit.setObjectName("Metre_LineEdit")
        self.Sinifi_LineEdit = QtWidgets.QLineEdit(self.details_groupBox_4)
        self.Sinifi_LineEdit.setGeometry(QtCore.QRect(360, 180, 201, 40))
        self.Sinifi_LineEdit.setStyleSheet("")
        self.Sinifi_LineEdit.setObjectName("Sinifi_LineEdit")
        self.label_11 = QtWidgets.QLabel(self.details_groupBox_4)
        self.label_11.setGeometry(QtCore.QRect(30, 180, 321, 37))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color:white;")
        self.label_11.setObjectName("label_11")
        self.Gunclle_PushButton = QtWidgets.QPushButton(self.details_groupBox_4)
        self.Gunclle_PushButton.setGeometry(QtCore.QRect(359, 250, 201, 51))
        self.Gunclle_PushButton.setStyleSheet("")
        self.Gunclle_PushButton.setObjectName("Gunclle_PushButton")
        self.Delete_PushButton = QtWidgets.QPushButton(self.details_groupBox_4)
        self.Delete_PushButton.setGeometry(QtCore.QRect(40, 250, 201, 51))
        self.Delete_PushButton.setStyleSheet("")
        self.Delete_PushButton.setObjectName("Delete_PushButton")
        self.gridLayout.addWidget(self.details_groupBox_4, 0, 2, 1, 1)
        self.details_groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.details_groupBox_3.setMaximumSize(QtCore.QSize(1901, 581))
        self.details_groupBox_3.setStyleSheet("")
        self.details_groupBox_3.setObjectName("details_groupBox_3")
        self.Veri_Tabani_Widget = QtWidgets.QTableWidget(self.details_groupBox_3)
        self.Veri_Tabani_Widget.setGeometry(QtCore.QRect(20, 30, 1871, 531))
        self.Veri_Tabani_Widget.setStyleSheet("")
        self.Veri_Tabani_Widget.setRowCount(1000)
        self.Veri_Tabani_Widget.setColumnCount(12)
        self.Veri_Tabani_Widget.setObjectName("Veri_Tabani_Widget")
        self.Veri_Tabani_Widget.horizontalHeader().setDefaultSectionSize(151)
        self.gridLayout.addWidget(self.details_groupBox_3, 1, 0, 1, 3)
        Veri_Tabani_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Veri_Tabani_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1940, 43))
        self.menubar.setObjectName("menubar")
        self.menuCamera = QtWidgets.QMenu(self.menubar)
        self.menuCamera.setObjectName("menuCamera")
        self.menuHakk_nda = QtWidgets.QMenu(self.menubar)
        self.menuHakk_nda.setObjectName("menuHakk_nda")
        self.menuAdmin_Paneli = QtWidgets.QMenu(self.menubar)
        self.menuAdmin_Paneli.setObjectName("menuAdmin_Paneli")
        self.menuKapat = QtWidgets.QMenu(self.menubar)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/MainWindow/mmm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuKapat.setIcon(icon)
        self.menuKapat.setObjectName("menuKapat")
        Veri_Tabani_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Veri_Tabani_Window)
        self.statusbar.setObjectName("statusbar")
        Veri_Tabani_Window.setStatusBar(self.statusbar)
        self.actionKameralar = QtWidgets.QAction(Veri_Tabani_Window)
        self.actionKameralar.setObjectName("actionKameralar")
        self.actionAdmin_Paneli = QtWidgets.QAction(Veri_Tabani_Window)
        self.actionAdmin_Paneli.setObjectName("actionAdmin_Paneli")
        self.actionHakk_nda = QtWidgets.QAction(Veri_Tabani_Window)
        self.actionHakk_nda.setObjectName("actionHakk_nda")
        self.action_k = QtWidgets.QAction(Veri_Tabani_Window)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icon/MainWindow/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_k.setIcon(icon1)
        self.action_k.setObjectName("action_k")
        self.menuCamera.addAction(self.actionKameralar)
        self.menuHakk_nda.addAction(self.actionHakk_nda)
        self.menuAdmin_Paneli.addAction(self.actionAdmin_Paneli)
        self.menuKapat.addAction(self.action_k)
        self.menubar.addAction(self.menuKapat.menuAction())
        self.menubar.addAction(self.menuCamera.menuAction())
        self.menubar.addAction(self.menuAdmin_Paneli.menuAction())
        self.menubar.addAction(self.menuHakk_nda.menuAction())

        self.retranslateUi(Veri_Tabani_Window)
        QtCore.QMetaObject.connectSlotsByName(Veri_Tabani_Window)

    def retranslateUi(self, Veri_Tabani_Window):
        _translate = QtCore.QCoreApplication.translate
        Veri_Tabani_Window.setWindowTitle(_translate("Veri_Tabani_Window", "Veri Tabanı"))
        self.details_groupBox_2.setTitle(_translate("Veri_Tabani_Window", "Filtre"))
        self.Goster_pushButton.setText(_translate("Veri_Tabani_Window", "Göster"))
        self.Temiz_pushButton.setText(_translate("Veri_Tabani_Window", "Temizle"))
        self.Leke_radioButton.setText(_translate("Veri_Tabani_Window", "Leke"))
        self.Delik_RadioButton.setText(_translate("Veri_Tabani_Window", "Delik"))
        self.Iplik_RadioButton.setText(_translate("Veri_Tabani_Window", "Iplik"))
        self.Yag_RadioButton.setText(_translate("Veri_Tabani_Window", "Yağ"))
        self.Yatay_RadioButton.setText(_translate("Veri_Tabani_Window", "Yatay"))
        self.Dikey_RadioButton.setText(_translate("Veri_Tabani_Window", "Dikey"))
        self.Tumu_RadioButton.setText(_translate("Veri_Tabani_Window", "Tumu"))
        self.Kirik_RadioButton.setText(_translate("Veri_Tabani_Window", "Kırık"))
        self.details_groupBox.setTitle(_translate("Veri_Tabani_Window", "KONTROL"))
        self.label_3.setText(_translate("Veri_Tabani_Window", "Başlangıç Tarihi:"))
        self.label_4.setText(_translate("Veri_Tabani_Window", "Bitiş Tarihi"))
        self.Listele_pushButton.setText(_translate("Veri_Tabani_Window", "Listele"))
        self.Raporla_PushButton.setText(_translate("Veri_Tabani_Window", "Raporla"))
        self.label_Dok_No.setText(_translate("Veri_Tabani_Window", "Dok No"))
        self.label_Kalite_No.setText(_translate("Veri_Tabani_Window", "Kalite No"))
        self.details_groupBox_4.setTitle(_translate("Veri_Tabani_Window", "KONTROL"))
        self.label_9.setText(_translate("Veri_Tabani_Window", "Hata Alanı(mm2)"))
        self.label_10.setText(_translate("Veri_Tabani_Window", "Hatanın Geldiği Metre(m)"))
        self.label_11.setText(_translate("Veri_Tabani_Window", "Hatanın Sınıfı"))
        self.Gunclle_PushButton.setText(_translate("Veri_Tabani_Window", "Güncelle"))
        self.Delete_PushButton.setText(_translate("Veri_Tabani_Window", "Sil"))
        self.details_groupBox_3.setTitle(_translate("Veri_Tabani_Window", "Veri Tabanı"))
        self.menuCamera.setTitle(_translate("Veri_Tabani_Window", "Kameralar"))
        self.menuHakk_nda.setTitle(_translate("Veri_Tabani_Window", "Hakkında"))
        self.menuAdmin_Paneli.setTitle(_translate("Veri_Tabani_Window", "Admin Paneli"))
        self.menuKapat.setTitle(_translate("Veri_Tabani_Window", "Kapat"))
        self.actionKameralar.setText(_translate("Veri_Tabani_Window", "Kameralar"))
        self.actionAdmin_Paneli.setText(_translate("Veri_Tabani_Window", "Admin Paneli"))
        self.actionHakk_nda.setText(_translate("Veri_Tabani_Window", "Hakkında"))
        self.action_k.setText(_translate("Veri_Tabani_Window", "Çıkış"))

